Add budget harmonization method
iiasa/aneris pull request #29
Opened 2020-08-28 15:24 UTC by coroa

2020-09-16 07:46 UTC, gidden commented
@coroa on this one, could you please rebase to only the commits related? I may have a few comments which would be easier to walk through as such.

2020-09-16 08:45 UTC, coroa commented
> @coroa on this one, could you please rebase to only the commits related? I may have a few comments which would be easier to walk through as such.

Done

2020-09-16 09:09 UTC, gidden requested changes
Thanks again @coroa - I have two doc requests, let me know if you think they are too much:

1. in the docstring for `budget` at minimum could you add a description of how this works (i.e., what is being minimized, constrained, etc.) and at maximum add the mathematical formulation?
2. we should also have already a tutorial notebook, could you port that here since this method is less 'transparent' and could very much use a visual explanation?

2020-09-16 09:09 UTC, gidden commented on aneris/methods.py
> +        """
Can this doc be removed?

2020-09-18 14:05 UTC, coroa commented
@gidden Please check whether the last commits, fulfill your requirements.

I have not used math in numpy docstrings before, I am not sure, whether sphinx will run fine with them. And a quick test reveal they are not working as i had expected. Should just have looked up docs before (https://numpydoc.readthedocs.io/en/latest/format.html). Anyway, feel free to suggest or adapt.

Otherwise i'll finish it on monday.

2020-09-24 12:28 UTC, gidden commented
Looks great, thanks @coroa !

2020-09-24 12:28 UTC, gidden approved these changes

2020-09-24 12:28 UTC, merged